### ISSUE TITLE
Localized additional info requires "@name:xy"

### ISSUE THREAD

**Issue by Ede123** [JasonBarnabe/greasyfork#355] opened 2015-04-21 17:20 UTC
When one tries to add localized additional information to a script an error message requests to add `"@name:xy"` meta key:
> Additional info was specified for the 'de' locale, but no @name:de was provided.

Is there any reason to require this? Actually names are often not translated, so adding localized additional information to a script which does not have a localized name seems totally valid (especially since localized meta keys and a localized description on Greasy Fork seem like two completely independent things for me).

This gets even more frustrating since the `"@name:xy"` meta key in turn requires a localized `"@description:xy"`, see issue #354.

Therefore to be able to add localized additional information, currently the author is forced to add both, `"@name:xy"` and `"@description:xy"` at the same time.

**Comment by JasonBarnabe** [comment] 2015-04-21 17:28
Greasy Fork requires `@name` and `@description`. This is an extension of that - if you're going to have localized content, you need to have at least `@name:xx` and `@description:xx`. If they're the same as in the base language, then just repeat it. Going through the list of top scripts on the site, most of them should have their names translated if they were to be translated, and all of them should have their descriptions translated.

**Comment by JasonBarnabe** [comment] 2015-05-04 15:05
Closing as this is as intended.

**Closed by JasonBarnabe** 2015-05-04 15:05 UTC
