### ISSUE TITLE
"Applies to:" includes duplicated entries

### ISSUE THREAD

**Issue by Ede123** [JasonBarnabe/greasyfork#374] opened 2015-07-21 15:35 UTC
Just stumbled over the following example:
https://greasyfork.org/en/scripts/7678-wikipedia-inline-article-viewer

"Applies to:" lists *wikipedia.org* two times and also the respective [by-site search](https://greasyfork.org/en/scripts/by-site/wikipedia.org) includes the exact same script two times.

I assume this shouldn't be happening...

**Comment by JasonBarnabe** [comment] 2015-07-28 02:39
Fixed now. It was caused by the combination of wikipedia.tld and wikipedia.org.

**Closed by JasonBarnabe** 2015-07-28 02:39 UTC
