### ISSUE TITLE
Support FireMonkey's UserCSS spec

### ISSUE THREAD

**Issue by r-a-y** [JasonBarnabe/greasyfork#656] opened 2020-03-13 01:09 UTC
FireMonkey supports user CSS, but uses a slightly different spec than the one used by Stylus.

I tried to post a userstyle using FireMonkey's syntax and it wasn't accepted on GreasyFork.

I believe it's because of these differences:
1. FireMonkey uses the `==UserCSS==` header and not `==UserStyle==`
2. FireMonkey utilizes the `@match` rule that is commonly used with userscripts to match the CSS for the correspondng site.  Whereas, Stylus requires using an `@moz-document` CSS rule to target the site.

Would it be possible to add some validation for FireMonkey's UserCSS?

Also see https://github.com/erosman/support/issues/111.

**Comment by eight04** [comment] 2020-03-13 03:15
Is there a link to Firemonkey's spec?

**Comment by r-a-y** [comment] 2020-03-13 03:28
I couldn't find a document online that outlines the spec (ping @erosman), but here's a simple UserCSS script so you can see the basic differences:

```
/*
==UserCSS==
@name    Wikipedia Dark Background
@match   https://*.wikipedia.org/*
@version 1.0
@run-at  document-end
==/UserCSS==
*/
body {background-color:#333;}
```

Using `@match` is way more elegant than having to use an `@moz-document` CSS rule to target the site you want to write custom CSS for.

**Comment by erosman** [comment] 2020-03-13 05:17
> **Metadata Block**
> 
> For easier compatibility, format is similar to GreaseMonkey Metadata Block for UserScripts. The commenting is different for CSS and as a result a uniform commenting for Metadata Block can be used. The Metadata Block identifier (**case-insensitive** e.g. ==userscript== etc) for UserScript is ==UserScript== ... ==/UserScript== and for UserCSS is ==UserCSS== ... ==/UserCSS==. 


Please let me know if there are any queries.

**Comment by JasonBarnabe** [comment] 2020-03-13 22:51
It would be fairly easier to make Greasy Fork support posting FireMonkey-format user styles, but my concern is around the UI for users. Effectively there's have to be a differentiation between ones you can install in Stylus and ones you can install in FireMonkey.

Greasy Fork has the ability to convert from user CSS to user JS. I wonder if there was some way it could covert whatever was entered into a format compatible with both managers.

**Comment by erosman** [comment] 2020-03-14 06:31
> my concern is around the UI for users. Effectively there's have to be a differentiation between ones you can install in Stylus and ones you can install in FireMonkey.

Maybe a category listing as:

- User-Script
- User-Style
- User-CSS

Although that doesn't look very nice :stuck_out_tongue: 

Alternatively a badge to say it is for FireMonkey.

> Greasy Fork has the ability to convert from user CSS to user JS.

It is very easy to convert FireMonkey userCSS to JS, although the overheads of userScripts (injection API, user-API, listeners etc) are far higher than userCSS in browser performance and it is generally not recommended.

Such conversion is considerable for users who have GM/TM/GM and dont want to install Stylish/Stylus/etc. The overheads in this case are somehow acceptable since one addons is installed instead of two.
The conversion (and converted) also can become resource-intensive when style for multiple sites are listed into one userStyle eg;

```CSS
@-moz-document regexp('https?:\/\/(www\.|old\.)?reddit.com.*') {
  /* --- css --- */
}

@-moz-document regexp('https?:\/\/(www\.|old\.)?more.com.*') {
  /* --- css --- */
}

@-moz-document url('http://www.site.com/test.html') {
  /* --- css --- */
}

@-moz-document domain('images.some.com'), url-prefix('http://other.com/images') {
  /* --- css --- */
}
```

FireMonkey support both user-script & user-CSS.

**Comment by JasonBarnabe** [comment] 2020-03-14 17:08
Right, I'm not suggesting we only support FireMonkey via Stylus user CSS to user JS conversion. I'm saying that there's already the ability to transform from one format to another. If we could get a format that both Stylus and FireMonkey support, then it could just convert any input to that.

Stylus has support for different formats via the `@preprocessor` rule. I wonder if they could add FireMonkey's format, or FireMonkey could be adapted to one of the existing formats.

**Comment by erosman** [comment] 2020-03-14 17:53
> there's already the ability to transform from one format to another

So far it is not possible to convert Stylus `@-moz-document regexp()` To FireMonkey userCSS since userContents/UserScritps API do not support RegExp.

It is possible to convert FireMonkey userCSS to Stylus userStyle though.

> Stylus has support for different formats via the @preprocessor rule

I had a quick look now. It seems that it refers to the type of CSS and not the matching process which is the issue here. (ref: https://github.com/openstyles/stylus/wiki/UserCSS-authors#preprocessor )

> I wonder if they could add FireMonkey's format

Stylus/Stylish (as well as GM/VM/TM) inject script & CSS via a manual method of checking each URL against the scripts/CSS every time.

FireMonkey uses the dedicated API and its format has no use for Stylus/Stylish.

> FireMonkey could be adapted to one of the existing formats.

In case of userStyle, the problem is the `@-moz-document regexp()` as mentioned above. There isn't any reliable way to convert regexp to match pattern.

`@-moz-document` (Firefox 1.5) has been experimental (already changed to [@document](https://developer.mozilla.org/en-US/docs/Web/CSS/@document)) and may be removed. It is not supported by any other browser.

**Comment by JasonBarnabe** [comment] 2020-03-14 18:11
It's fine if there are certain features that make it non-convertible. This already the case in user CSS to user JS conversion. But if we can get the majority working in both Stylus and FireMonkey that would be ideal. We should be working towards greater compatibility (like in user scripts) even if things are not 100% perfect.

FYI, Stylus works on Chrome too, where there is no `@-moz-document` support.

**Comment by erosman** [comment] 2020-03-14 18:44
> FYI, Stylus works on Chrome too, where there is no @-moz-document support.

To be exact, Stylus doesnt use `@-moz-document`.

In legacy Firefox, addon could write to Firefox CSS directly. `@-moz-document` is supported by Firefox legacy style sheets like userContent.css, userChrome.css
Extensions could then write `@-moz-document` directly and Firefox would process them.

Since Firefox quantum (57) extensions can no longer do that. In fact above style-sheets are due to be removed.

Stylus/Stylish etc now de-construct `@-moz-document` by converting them to a individual Regexes (or rules that can be checked with `url.startsWith()` etc) and then add a listener to tab & web request and then check the url against these created RegExes & rules.

Therefore the format `@-moz-document` is only kept for compatibility with userStyles written for legacy Firefox.

**Comment by eight04** [comment] 2020-03-15 06:10
For Firemonkey

1. Is it possible to make Firemonkey support Stylus's usercss format i.e. legacy `@-moz-document`? The major difference is that one style may contain multiple sections which can use different match rules. A CSS parser is needed to extract each section.
2. Throw an error if a user try to install a style using regexp functions. (This can be fixed by implementing regexp matching in webextension API.)
3. Firemonkey can support `@preprocessor` directive by including the compiler in the extension. If this is not an option, throw an error like (2).

For stylus

1. Support `@match` directive. Therefore users can install Firemonkey styles in Stylus. It will also be smoother if someone wants to convert Firemonkey styles to Stylus usercss.
2. Support `@noframes` directive? AFAIK, scripts/styles runs in frames by default (Tampermonkey/Stylish/Stylus). It seems that Firemonkey works in the opposite way?

I think GreasyFork doesn't have to do any conversion to the source code. Scripts/styles may have compatibility issues in different managers anyway. However, I suggest using the same header keyword for consistency. (Stylus uses `==UserStyle==` to be compatible with xStyle though many syntax are still different)

**Comment by erosman** [comment] 2020-03-17 05:46
> From: [@document](https://developer.mozilla.org/en-US/docs/Web/CSS/@document)
> 
> Implemented with the vendor prefix: `-moz-`
> 
> **Notes Disabled by default in web pages**, except for an empty `url-prefix()` value, which is supported due to its use in Firefox browser detection. Still supported in **user stylesheets**.
> 
> Disabled From version 61: this feature is behind the `layout.css.moz-document.content.enabled` preference (needs to be set to true). To change preferences in Firefox, visit `about:config`.


:thought_balloon:  I can convert all userStyle that dont have `@-moz-document regexp()` to multiple userCSS ... or .... single userScript :thinking:

**Comment by erosman** [comment] 2020-03-17 07:55
PS. I see GreasyFork supports `@compatible `
Can that be used? .e.g 
```
@compatible              FireMonkey
```

**Comment by erosman** [comment] 2020-03-18 07:21
ref: Support include/exclude in usercss header #343

> The only problem is that Firemonkey only supports single section style.

That is how the Firefox API works. Even if a multi section CSS is supported, it has to be broken into individual segments every time in order to register it with the Firefox (or Chrome) API since there is no way for the CSS to apply rules conditionally based on URL (`@document` is not supported yet, postponed to CSS4).

**Comment by erosman** [comment] 2020-03-18 19:22
FireMonkey: for the next release

Partial compatibility with **standard CSS syntax** UserStyle `==UserStyle== ... ==/UserStyle==` is also available (v1.34). Few basic `regexp()` are converted to match pattern but other sections with `regexp()` are ignored as browser API does not support Regular Expression.

The default 'run-at' is set to 'document-start' for UserStyles.

Therefore the FireMonkey meatadata setup is:

- UserScript
- UserCSS (same as UserScript)
- UserStyle

**Comment by eight04** [comment] 2020-03-20 12:13
> Since the handling is going to be different, I think it is better to keep the `UserCSS` for FireMonkey native and `UserStyle` for Stylus etc compatibility.

Do you mean that you don't accept `@match` for `==UserStyle==`? I planned to make it work for the global section. (From Stylus' sight, all Firemonkey styles are single global section styles)

**Comment by erosman** [comment] 2020-03-20 14:38
> Do you mean that you don't accept @match for ==UserStyle==? I planned to make it work for the global section. (From Stylus' sight, all Firemonkey styles are single global section styles)

@eight04  Actually, FireMonkey (1.34) processes all supported metadata block entries all the time, therefore the `@match` will be processed for UserStyle as well.

However, if there is `@-moz-document` in the code, then `@-moz-document` functions will be used.

To clarify ...............

### On Save Script
- In all cases (UserScript. UserCSS & UserStyle) all supported metadata block entries will be processed
- In case of UserStyle (only), FireMonkey also parses the content and looks for `@-moz-document` and if present then:
  - Parses all `url | url-prefix | domain` (and some very basic `regexp` only) and converts them match pattern for each section and
  -  Saves them in `{matches, css}` sets in a separate array (`style: []`)

### On Register Script
- In all cases, the relevant entries (e.g. `matches | excludeMatches | includeGlobs | excludeGlobs | matchAboutBlank | allFrames | runAt` etc) are processed for registration with API for injection
- If `style: []` is not empty (which would be in case of UserStyle WITH `@-moz-document` ), then FireMonkey uses the `{matches, css}` stored in `style`, and NOT the in `@matches` from metadata block, and registers multiple CSS


**Notes:**

- Only the first metadata block is processed
- Sections will only be processed for UserStyle with `@-moz-document`
- A UserStyle without `@-moz-document` would be processed just like a UserCSS
- Mixture of `@match` & `@-moz-document` will not work (`@match` will be ignored)
- The separation of UserCSS & UserStyle is that in case of UserStyle, FireMonkey also parses the content and look for `@-moz-document`
- Only the **standard CSS syntax** is supported (ref `@preprocessor`) unless Firefox support SASS, LESS , SCSS (I didn't find the relevant info)

**Comment by erosman** [comment] 2020-04-02 12:47
Just for Info:

FireMonkey 1.34 was released with support for UserStyle in addition to UserScript & UserCSS

**Comment by almaceleste** [comment] 2020-05-29 23:28
@erosman, is your extension related to the FireMonkey FMX framework of the Embarcadero Technologies company?
if no, I think you chose a not-so-good name for your extension.

**Comment by erosman** [comment] 2020-05-30 04:05
> @erosman, is your extension related to the FireMonkey FMX framework of the Embarcadero Technologies company?
if no, I think you chose a not-so-good name for your extension.

Not related at all.

AFA name, it is derived from **Fire** + _fox_ + *** + **Monkey** => FireMonkey

Name similarities are common in products and usually, if they are not within the same field, they are tolerated (unless both product become commercial and competing).

If there is a legal reason for changing the name, I will do so.

**Comment by almaceleste** [comment] 2020-05-30 05:21
ok, I don't care. it's not my affair at all. 
but when I read about FireMonkey here, I try to google about it and found only links to the FireMonkey FMX framework and Embarcadero Technologies. but nothing about you and your extension. 
I think this is not good for product advance. 
anyway this does not apply to the topic
buena suerte, @erosman

**Comment by erosman** [comment] 2020-05-30 07:00
`FireMonky + Firefox` would be the right search parameter (or `FireMonky + userscript`).
FireMonkey is still the new kid on the block. Hopefully that will change over time.

**Comment by JasonBarnabe** [comment] 2020-05-30 15:13
If there are specific things the site can do do support FireMonkey, let me know. As I mentioned above, I am against having a completely different format for different extensions if it can be helped.

**Closed by JasonBarnabe** 2020-05-30 15:13 UTC

**Comment by erosman** [comment] 2020-05-30 15:23
> If there are specific things the site can do do support FireMonkey, let me know
@JasonBarnabe FireMonkey supports UserScript, UserStyle & UserCSS (case-insensitive) metadata block (with some limitation).

GreasyFork at the moment supports UserScript, UserStyle.
It is only UserCSS support that can be added to GreasyFork if desired.

All above use the exact same format/parameters in FireMonkey which is similar to GM.
