### ISSUE TITLE
Registration rejects e-mail addresses with "+" in them

### ISSUE THREAD

**Issue by cweiske** [JasonBarnabe/greasyfork#871] opened 2021-02-08 12:01 UTC
The registration page at https://greasyfork.org/de/users/sign_up rejects e-mails that have a `+` in the user part, e.g. `user+greasyfork.org@example.org`.

Such e-mail addresses are valid, and are a common practice to detect where e-mail addresses got leaked and later used for spam.

Please allow `+` in e-mail addresses

**Comment by JasonBarnabe** [comment] 2021-02-08 20:29
There is no prohibition against `+`. It does check that the domain you use is a valid domain that could receive email. That example is not valid; is that what you're actually trying?

**Comment by cweiske** [comment] 2021-02-09 05:35
No, I am trying `cweiske+greasyfork.org@cweiske.de`.

The form says: 
> 1 error prohibited this user from being saved:
> Email is invalid

**Comment by JasonBarnabe** [comment] 2021-02-09 15:06
The problem is with the `.` in `greasyfork.org`. The library we use for validation doesn't allow that. I've filed https://github.com/afair/email_address/issues/69.

**Comment by JasonBarnabe** [comment] 2021-02-13 02:59
Should be fixed now.

**Closed by JasonBarnabe** 2021-02-13 02:59 UTC
