### ISSUE TITLE
My script can't be accessed after manual synchronization fails.

### ISSUE THREAD

**Issue by techmovie** [JasonBarnabe/greasyfork#884] opened 2021-04-10 19:35 UTC
https://greasyfork.org/zh-CN/scripts/423199-easy-seed-pt%E4%B8%80%E9%94%AE%E8%BD%AC%E7%A7%8D

**Comment by xiaopangju** [comment] 2021-04-10 22:56
我注意到网址中的缩略名中似乎有汉字，你认为是因为这个原因吗？

**Comment by xiaopangju** [comment] 2021-04-10 22:57
Duplicate of #883

**Comment by JasonBarnabe** [comment] 2021-04-12 00:05
I think it's unlikely the two things are related. Investigating...

**Comment by JasonBarnabe** [comment] 2021-04-12 00:33
There's some sort of issue with mentions (`@username`). At one point, the script had `@require` (unescaped) in its description, and there happens to be a user with that name. What I found is that with every update of the script, this stored mention got duplicated. It was up to the tens of thousands, which caused the page to be very slow.

I'm not sure why this would occur, especially since newer versions of the page did not do this mention. I would be curious @techmovie to check after your next update, if it's still creating phantom mentions.

**Comment by techmovie** [comment] 2021-04-12 02:44
> There's some sort of issue with mentions (`@username`). At one point, the script had `@require` (unescaped) in its description, and there happens to be a user with that name. What I found is that with every update of the script, this stored mention got duplicated. It was up to the tens of thousands, which caused the page to be very slow.
> 
> I'm not sure why this would occur, especially since newer versions of the page did not do this mention. I would be curious @techmovie to check after your next update, if it's still creating phantom mentions.

okay, thank you for your help

**Comment by JasonBarnabe** [comment] 2021-04-13 02:18
There are no new mentions created after the latest update to the script. I can however reproduce this simply by creating an additional info with a mention then updating.

**Comment by techmovie** [comment] 2021-04-13 06:16
> additional info

What does  this additional info mean for?

**Comment by JasonBarnabe** [comment] 2021-08-13 01:49
The case of mentions on additional info getting duplicated on update should be fixed now,

**Closed by JasonBarnabe** 2021-08-13 01:49 UTC
