### ISSUE TITLE
Scripts disappear from the "by-site" listings

### ISSUE THREAD

**Issue by Procyon-b** [JasonBarnabe/greasyfork#823] opened 2020-11-25 15:30 UTC
2 of my scripts have disappeared from their corresponding "by-site" listings. (I say "2" because I only tested for those 2)
Last night they were still present, but today they are gone. I noticed when I saw the "daily installs" decreasing.
And searching with a specific term doesn't bring it in the results anymore. I also tried without being identified.

user: 435938
scripts: 412178 and 403031

**Comment by Procyon-b** [comment] 2020-11-25 16:51
The scripts are back in the listing.

**Comment by JasonBarnabe** [comment] 2020-11-25 16:53
Thanks for the report. I'm trying to track down the issue and it's helpful to know when it happens.

**Comment by Procyon-b** [comment] 2020-11-25 16:58
I see now (on a listing with very few scripts) that styles are listed by default even when "JavaScript" is selected by default under "language"
`/en/scripts/by-site/gmx.net`  ("...blue buttons")


The issue above: could this be related with my account not having a locale selected by default?

**Comment by JasonBarnabe** [comment] 2020-11-25 17:00
Styles are listed with the JavaScript option selected if they are convertible to JavaScript (they'll have both "Install as User Script" and "Install as User Style" buttons). This is expected and as intended.

Should not have anything to do with locales.

**Comment by Procyon-b** [comment] 2020-11-25 17:15
Styles: I didn't notice before. (the 2 buttons, yes ; but not the difference regarding the listings)

Locales: I was thinking of one thing that I haven't set compared to other users. (I know I can mess things with one line in my own programs  ;)  )

**Comment by JasonBarnabe** [comment] 2020-11-26 22:30
The issue appears to be oom-killer killing sidekiq while an indexing job is running, leaving `script_delta.tmp`, which is doesn't like. Not sure why it's running out of memory, but I'm gonna see if I can put in a cron job to detect this and fix.

**Comment by Procyon-b** [comment] 2020-11-26 22:54
Is it killed every time or only once in a while?

I also noticed (but it's fixed now) that the diff job for "derivatives" wasn't executed (that didn't work at least for a week or two).
I mention this in case it could be related.

**Comment by Procyon-b** [comment] 2020-11-26 22:58
I haven't touched a linux machine for a long time. I had to look up what "oom-killer" was.   :)

**Comment by JasonBarnabe** [comment] 2020-11-27 00:18
> Is it killed every time or only once in a while?

Maybe once a day.

> I also noticed (but it's fixed now) that the diff job for "derivatives" wasn't executed (that didn't work at least for a week or two).

There was a recent change making soft-deleted scripts checked as well, which caused a backlog as there were a bunch of them. I changed it again to prioritize non-deleted scripts.

**Comment by JasonBarnabe** [comment] 2020-12-02 01:55
Has not reoccurred, marking as closed.

**Closed by JasonBarnabe** 2020-12-02 01:55 UTC

**Comment by Procyon-b** [comment] 2020-12-02 18:01
Just noticed that a script has a very low installation rate today. But it is present in the site index and in search results. So maybe unrelated.
script `412178`
